# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9dbdfbb4879493ab587ca047e9b760d1b45d90cf9e0a9d2beba3ad91fd587d2c2b060b94d6d40c8799136a69eb7e5c8e9a2cc4267c832cad5655d994145c2918

test:
  secret_key_base: dca1e09b04fb9592f279bfc2329628a30097cfbc56ad07c42366f4b09fda9f683bd8d334aeebc55de2a5d6f44323b2f508d72ee2a3ee21b96fd45c34defdee59

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
